name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - name: Install modules
      run: yarn

    - name: Run tests
      run: yarn test
